"""
Django settings for quick_lab project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from . info import *
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#C:\Users\abdel\AppData\Local\Programs\Python\Python311\python.exe -m venv newvenv
#.\newvenv\Scripts\activate
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e7-pm((4vl*7w0m^&k!b=-ud-n4e^++55-_aum1nnod&=-@oaf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['105.106.197.40' ,'192.168.1.109', 'zakiquicklab.duckdns.org']
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.109', '192.168.218.171','105.107.183.166','zakiquicklab.duckdns.org']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Set secure cookies
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'admin',
#     'login',
#     'patient',
#     'directeur',
#     'infirmier',
#     'medecin_chef',
#     'receptionniste',
# ]

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accueill',
    'admin',
    'login',
    'patient',
    'directeur',
    'infirmier',
    'medecin_chef',
    'receptionniste',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quick_lab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quick_lab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {  
    'default': {  
        'ENGINE': 'django.db.backends.mysql',  
        'NAME': 'quick_lab',  
        'USER':'root',  
        'PASSWORD':'04122002',  
        'HOST':'localhost',  
        'PORT':'3306'  
    }  
} 


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Algiers'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


STATIC_URL = '/static/'
#STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# PDF files
SPECIAL_MEDIA_URL = '/pdf/'
SPECIAL_MEDIA_ROOT = os.path.join(BASE_DIR, 'pdf')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_PORT = EMAIL_PORT

AUTH_USER_MODEL = 'login.Personne'
AUTHENTICATION_BACKENDS = [
    'login.backends.PersonneBackend',
    'admin.backends.AdminBackend',   
]

LOGIN_URL = '/login/'

STRIPE_PUBLISHABLE_KEY = STRIPE_PUBLISHABLE_KEY
STRIPE_SECRET_KEY = STRIPE_SECRET_KEY
STRIPE_ENDPOINT_SECRET = STRIPE_ENDPOINT_SECRET



CSRF_TRUSTED_ORIGINS = [
    'https://192.168.1.109',
    'http://localhost',
    'https://127.0.0.1', 
    'https://105.107.183.166',
    'https://192.168.218.171',
    'https://zakiquicklab.duckdns.org',
    # Add any other trusted origins here
]

