# Generated by Django 4.2 on 2023-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('type_abonnement', models.CharField(blank=True, max_length=7, null=True)),
                ('statut', models.CharField(blank=True, max_length=10, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'abonnement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('prenom', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('mot_de_pass', models.CharField(blank=True, max_length=45, null=True)),
                ('sex', models.CharField(blank=True, max_length=45, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_last4', models.CharField(max_length=4)),
                ('card_brand', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment_lab',
                'managed': False,
            },
        ),
    ]
