# Generated by Django 4.2 on 2023-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PocheSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ml', models.IntegerField()),
                ('is_accepted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poche_sang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rapport', models.TextField(blank=True, null=True)),
                ('is_validate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rapport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultatRapportPdf',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chemin', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'resultat_rapport_pdf',
                'managed': False,
            },
        ),
    ]
