# Generated by Django 4.2 on 2023-04-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('num_telephone', models.CharField(max_length=13, unique=True)),
                ('nom_utilisateur', models.CharField(max_length=45, unique=True)),
                ('mot_passe', models.CharField(max_length=45)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'personne',
                'managed': False,
            },
        ),
    ]
