# Generated by Django 4.2 on 2023-06-01 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('branche_nom', models.CharField(blank=True, max_length=120, null=True)),
                ('localisation', models.CharField(blank=True, max_length=45, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('num_telephone', models.CharField(blank=True, max_length=13, null=True)),
                ('jour_heur_tarvail', models.TextField(blank=True, null=True)),
                ('num_rdv', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branche',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directeur',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'directeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'laboratoire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('maladie', models.TextField(blank=True, null=True)),
                ('type_sang', models.CharField(max_length=3, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.employe')),
            ],
            options={
                'db_table': 'infirmier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedecinChef',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.employe')),
            ],
            options={
                'db_table': 'medecin_chef',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptionniste',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.employe')),
            ],
            options={
                'db_table': 'receptionniste',
                'managed': False,
            },
        ),
    ]
