# Generated by Django 4.2 on 2023-06-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_branche_directeur_employe_laboratoire_patient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directeur',
        ),
    ]
