# Generated by Django 4.2 on 2023-06-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_branche_directeur_employe_laboratoire_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'annulation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Canaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'canaux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emetteur', models.CharField(max_length=11)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'communication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conseille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conseille', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conseille',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConseilleAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'conseille_analyse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('statut', models.CharField(blank=True, max_length=7, null=True)),
                ('chemin_facture', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_last4', models.CharField(max_length=4)),
                ('card_brand', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('heur', models.TimeField(blank=True, null=True)),
                ('analyes', models.TextField(blank=True, null=True)),
                ('type_rdv', models.CharField(blank=True, max_length=8, null=True)),
                ('etat', models.CharField(blank=True, max_length=9, null=True)),
                ('purpose', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'rendez_vous',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TravailInfermier',
            fields=[
                ('id_infermier', models.OneToOneField(db_column='id_infermier', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.infirmier')),
                ('is_terminer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travail_infermier',
                'managed': False,
            },
        ),
    ]
