# Generated by Django 4.2 on 2023-06-01 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_branche_directeur_employe_laboratoire_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('branche_nom', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('localisation', models.CharField(blank=True, max_length=45, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('num_telephone', models.CharField(blank=True, max_length=13, null=True)),
                ('jour_heur_tarvail', models.TextField(blank=True, null=True)),
                ('num_rdv', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branche',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientLabo',
            fields=[
                ('id_patient', models.OneToOneField(db_column='id_patient', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.patient')),
                ('is_bloked', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_labo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directeur',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='directeur_directeur', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_lab', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'directeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'laboratoire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrixAnalyse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'prix_analyse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeAnalyse',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_analyse', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'type_analyse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='directeur.employe')),
            ],
            options={
                'db_table': 'infirmier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedecinChef',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='directeur.employe')),
            ],
            options={
                'db_table': 'medecin_chef',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receptionniste',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='directeur.employe')),
            ],
            options={
                'db_table': 'receptionniste',
                'managed': False,
            },
        ),
    ]
